/**
 * Aggregate `#[command(...)]` descriptors into a CLI dispatcher module.
 *
 * Walks every compiled `.tsb`-output `.ts`, harvests `__command_*`
 * exports, and emits a single TS file that:
 *
 *   1. Re-exports the command handlers under their registered names.
 *   2. Exports a `dispatch(argv)` function that picks the matching
 *      command and coerces argv into the handler's typed parameters.
 *
 * Argument coercion is intentionally minimal: positional argv mapped to
 * parameter order, with `string`/`number`/`boolean` parsed. Anything
 * else is passed through as a string and the user can cast.
 */
import * as path from "node:path";
import { pathToFileURL } from "node:url";
import { buildProject } from "./compile.ts";

export interface CliAssemblerOptions {
  sourceGlobs: string[];
  cwd: string;
  /** Output path for the generated dispatcher (default `cli-app.ts`). */
  output?: string;
  macroModules?: string[];
  log?: (msg: string) => void;
}

interface CommandDescriptor {
  name: string;
  description: string;
  params: { name: string; type: string }[];
  /** Compiled-module path (absolute) the command was harvested from. */
  modulePath: string;
  /** Original export name (e.g. `__command_addBook` -> `addBook`). */
  exportName: string;
}

export async function buildCli(opts: CliAssemblerOptions): Promise<string> {
  const log = opts.log ?? ((m) => console.log(m));

  const outputs = await buildProject({
    sourceGlobs: opts.sourceGlobs,
    cwd: opts.cwd,
    macroModules: opts.macroModules,
    log,
  });

  const commands: CommandDescriptor[] = [];
  for (const tsPath of outputs) {
    for (const d of await collectCommands(tsPath)) commands.push(d);
  }

  const outPath = path.resolve(opts.cwd, opts.output ?? "cli-app.ts");
  const dispatcher = renderDispatcher(commands, outPath);
  await Bun.write(outPath, dispatcher);
  log(`wrote ${path.relative(opts.cwd, outPath) || outPath}`);
  return outPath;
}

async function collectCommands(tsPath: string): Promise<CommandDescriptor[]> {
  const url = pathToFileURL(tsPath).href;
  let mod: Record<string, unknown>;
  try {
    mod = (await import(url)) as Record<string, unknown>;
  } catch {
    return [];
  }
  const out: CommandDescriptor[] = [];
  for (const [key, value] of Object.entries(mod)) {
    if (!key.startsWith("__command_")) continue;
    if (!value || typeof value !== "object") continue;
    const v = value as { name?: string; description?: string; params?: { name: string; type: string }[] };
    if (typeof v.name !== "string") continue;
    out.push({
      name: v.name,
      description: v.description ?? "",
      params: v.params ?? [],
      modulePath: tsPath,
      exportName: key.slice("__command_".length),
    });
  }
  return out;
}

function renderDispatcher(commands: readonly CommandDescriptor[], outPath: string): string {
  const importsByPath = new Map<string, Set<string>>();
  for (const c of commands) {
    const rel = relativeImport(outPath, c.modulePath);
    const set = importsByPath.get(rel) ?? new Set<string>();
    set.add(c.exportName);
    importsByPath.set(rel, set);
  }
  const importLines: string[] = [];
  for (const [rel, names] of importsByPath) {
    importLines.push(`import { ${[...names].join(", ")} } from ${JSON.stringify(rel)};`);
  }

  const tableEntries = commands
    .map((c) => `  ${JSON.stringify(c.name)}: { description: ${JSON.stringify(c.description)}, params: ${JSON.stringify(c.params)}, handler: ${c.exportName} as unknown as (...args: unknown[]) => unknown }`)
    .join(",\n");

  return `// AUTO-GENERATED by bunny — do not edit by hand.
${importLines.join("\n")}

export interface CommandSpec {
  description: string;
  params: { name: string; type: string }[];
  handler: (...args: unknown[]) => unknown;
}

export const commands: Record<string, CommandSpec> = {
${tableEntries}
};

/**
 * Dispatch a positional argv against the command table. Coerces each
 * positional value to the parameter's declared type (\`string\`,
 * \`number\`, \`boolean\`); other types pass through as strings.
 */
export async function dispatch(argv: readonly string[]): Promise<unknown> {
  const [name, ...rest] = argv;
  if (!name) {
    printHelp();
    return undefined;
  }
  if (name === "--help" || name === "-h" || name === "help") {
    printHelp();
    return undefined;
  }
  const cmd = commands[name];
  if (!cmd) {
    process.stderr.write(\`unknown command: \${name}\\n\`);
    printHelp();
    process.exitCode = 1;
    return undefined;
  }
  const coerced = cmd.params.map((p, i) => coerce(rest[i], p.type));
  return await cmd.handler(...coerced);
}

function coerce(raw: string | undefined, type: string): unknown {
  if (raw === undefined) return undefined;
  const t = type.trim();
  if (t === "number") return Number(raw);
  if (t === "boolean") return raw === "true" || raw === "1";
  return raw;
}

function printHelp(): void {
  const rows = Object.entries(commands).map(([name, spec]) => {
    const sig = spec.params.map((p) => \`<\${p.name}>\`).join(" ");
    return \`  \${name} \${sig}\${spec.description ? "  — " + spec.description : ""}\`;
  });
  process.stdout.write("Commands:\\n" + rows.join("\\n") + "\\n");
}
`;
}

function relativeImport(from: string, to: string): string {
  const rel = path.relative(path.dirname(from), to);
  const norm = rel.startsWith(".") ? rel : `./${rel}`;
  return norm.replace(/\\/g, "/");
}
