/**
 * Aggregate `#[get/post/...]` route descriptors into a typed fetch
 * client module.
 *
 *   bunny client -s '**\/*.tsb' -o client.ts
 *
 * Each route becomes an exported async function whose argument and
 * return types are pulled from the handler's signature via TS
 * inference (no runtime type info is shipped). Path params are
 * interpolated into the URL; non-path params on POST/PUT/PATCH go in
 * the JSON body; on other methods they go into the query string.
 *
 * The client honours a `BUNNY_BASE_URL` env var when running on
 * Node/Bun, defaulting to the empty string (relative requests — useful
 * when the client is served from the same origin as the API).
 */
import * as path from "node:path";
import { pathToFileURL } from "node:url";
import { buildProject } from "./compile.ts";

export interface ClientAssemblerOptions {
  sourceGlobs: string[];
  cwd: string;
  output?: string;
  macroModules?: string[];
  log?: (msg: string) => void;
}

interface RouteDescriptor {
  method: string;
  path: string;
  params: { name: string; type: string }[];
  modulePath: string;
  exportName: string;
}

export async function buildClient(opts: ClientAssemblerOptions): Promise<string> {
  const log = opts.log ?? ((m) => console.log(m));
  const outputs = await buildProject({
    sourceGlobs: opts.sourceGlobs,
    cwd: opts.cwd,
    macroModules: opts.macroModules,
    log,
  });

  const routes: RouteDescriptor[] = [];
  for (const tsPath of outputs) {
    for (const r of await collect(tsPath)) routes.push(r);
  }

  const outPath = path.resolve(opts.cwd, opts.output ?? "client.ts");
  await Bun.write(outPath, renderClient(routes, outPath));
  log(`wrote ${path.relative(opts.cwd, outPath) || outPath}`);
  return outPath;
}

async function collect(tsPath: string): Promise<RouteDescriptor[]> {
  const url = pathToFileURL(tsPath).href;
  let mod: Record<string, unknown>;
  try {
    mod = (await import(url)) as Record<string, unknown>;
  } catch {
    return [];
  }
  const out: RouteDescriptor[] = [];
  for (const [key, value] of Object.entries(mod)) {
    if (!key.startsWith("__route_")) continue;
    if (!value || typeof value !== "object") continue;
    const v = value as {
      method?: string;
      path?: string;
      params?: { name: string; type: string }[];
    };
    if (typeof v.method !== "string" || typeof v.path !== "string") continue;
    out.push({
      method: v.method,
      path: v.path,
      params: v.params ?? [],
      modulePath: tsPath,
      exportName: key.slice("__route_".length),
    });
  }
  return out;
}

function renderClient(routes: readonly RouteDescriptor[], outPath: string): string {
  // Type-only imports under aliases so the generated function names can
  // shadow the handler names without conflict.
  const typeImportsByPath = new Map<string, Set<string>>();
  for (const r of routes) {
    const rel = relativeImport(outPath, r.modulePath);
    const set = typeImportsByPath.get(rel) ?? new Set<string>();
    set.add(`${r.exportName} as _${r.exportName}_t`);
    typeImportsByPath.set(rel, set);
  }
  const typeImportLines = [...typeImportsByPath].map(
    ([rel, names]) => `import type { ${[...names].join(", ")} } from ${JSON.stringify(rel)};`
  );

  const functions = routes.map(renderFunction).join("\n\n");

  return `// AUTO-GENERATED by bunny — do not edit by hand.
${typeImportLines.join("\n")}

export class BunnyClientError extends Error {
  constructor(public readonly status: number, message: string) {
    super(message);
    this.name = "BunnyClientError";
  }
}

/**
 * Base URL prepended to every request path. Reads from the
 * \`BUNNY_BASE_URL\` env var when running on Node/Bun; defaults to the
 * empty string so the browser sends relative requests to its own
 * origin. Override at runtime by assigning to \`baseUrl\`.
 */
export let baseUrl: string =
  typeof process !== "undefined" && (process as { env?: Record<string, string | undefined> }).env?.BUNNY_BASE_URL
    ? (process as { env: Record<string, string | undefined> }).env.BUNNY_BASE_URL!
    : "";

async function call(
  method: string,
  url: string,
  options?: { body?: unknown; query?: Record<string, unknown> }
): Promise<unknown> {
  let finalUrl = baseUrl + url;
  if (options?.query) {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(options.query)) {
      if (v !== undefined && v !== null) qs.append(k, String(v));
    }
    const s = qs.toString();
    if (s.length > 0) finalUrl += "?" + s;
  }
  const init: RequestInit = { method };
  if (options?.body !== undefined) {
    init.headers = { "Content-Type": "application/json" };
    init.body = JSON.stringify(options.body);
  }
  const res = await fetch(finalUrl, init);
  if (!res.ok) {
    throw new BunnyClientError(res.status, \`\${method} \${url} failed: \${res.status}\`);
  }
  // 204s have no body.
  if (res.status === 204) return undefined;
  const text = await res.text();
  return text.length === 0 ? undefined : JSON.parse(text);
}

${functions}
`;
}

function renderFunction(r: RouteDescriptor): string {
  const pathParamNames = new Set(
    [...r.path.matchAll(/:([A-Za-z_][A-Za-z0-9_]*)/g)].map((m) => m[1]!)
  );
  const hasBody = ["POST", "PUT", "PATCH"].includes(r.method);

  // Build the argument list. Each param uses `Parameters<typeof _fn_t>[i]`
  // so the client signature stays in lockstep with the handler's.
  const args: string[] = [];
  let bodyParam: string | undefined;
  const queryParams: string[] = [];
  let i = 0;
  for (const p of r.params) {
    const ty = `Parameters<typeof _${r.exportName}_t>[${i}]`;
    args.push(`${p.name}: ${ty}`);
    if (pathParamNames.has(p.name)) {
      // path-bound
    } else if (hasBody && !bodyParam) {
      bodyParam = p.name;
    } else {
      queryParams.push(p.name);
    }
    i++;
  }

  // Build the URL template by replacing each `:name` with the interpolated arg.
  let urlTemplate = "`" + r.path;
  for (const n of pathParamNames) {
    urlTemplate = urlTemplate.replace(`:${n}`, `\${encodeURIComponent(String(${n}))}`);
  }
  urlTemplate += "`";

  const callArgs: string[] = [`"${r.method}"`, urlTemplate];
  const optsParts: string[] = [];
  if (bodyParam) optsParts.push(`body: ${bodyParam}`);
  if (queryParams.length > 0) {
    optsParts.push(`query: { ${queryParams.join(", ")} }`);
  }
  if (optsParts.length > 0) {
    callArgs.push(`{ ${optsParts.join(", ")} }`);
  }

  const returnType = `Awaited<ReturnType<typeof _${r.exportName}_t>>`;
  return `export async function ${r.exportName}(${args.join(", ")}): Promise<${returnType}> {
  return (await call(${callArgs.join(", ")})) as ${returnType};
}`;
}

function relativeImport(from: string, to: string): string {
  const rel = path.relative(path.dirname(from), to);
  const norm = rel.startsWith(".") ? rel : `./${rel}`;
  return norm.replace(/\\/g, "/");
}
