/**
 * Aggregate `#[derive(Event)]` payloads + `#[onEvent(Name)]` listeners
 * from compiled `.tsb` outputs into a single bus module.
 *
 * Walks every `__event_*` and `__listener_*` module-level export, groups
 * listeners by event name, and emits:
 *
 *   - a `Events` union type of every event name
 *   - a `subscribe(event, handler)` for ad-hoc listeners
 *   - an `emit(event, payload)` that awaits every registered listener
 *
 * Listener export names that don't match any registered event are kept
 * but flagged as a diagnostic — the dispatch table still routes them by
 * the name they registered with.
 */
import * as path from "node:path";
import { pathToFileURL } from "node:url";
import { buildProject } from "./compile.ts";

export interface EventsAssemblerOptions {
  sourceGlobs: string[];
  cwd: string;
  output?: string;
  macroModules?: string[];
  log?: (msg: string) => void;
}

interface EventDescriptor { name: string; modulePath: string }
interface ListenerDescriptor {
  event: string;
  modulePath: string;
  exportName: string;
}

export async function buildEvents(opts: EventsAssemblerOptions): Promise<string> {
  const log = opts.log ?? ((m) => console.log(m));
  const outputs = await buildProject({
    sourceGlobs: opts.sourceGlobs,
    cwd: opts.cwd,
    macroModules: opts.macroModules,
    log,
  });

  const events: EventDescriptor[] = [];
  const listeners: ListenerDescriptor[] = [];
  for (const tsPath of outputs) {
    const { events: es, listeners: ls } = await collect(tsPath);
    events.push(...es);
    listeners.push(...ls);
  }

  const outPath = path.resolve(opts.cwd, opts.output ?? "bus.ts");
  await Bun.write(outPath, renderBus(events, listeners, outPath));
  log(`wrote ${path.relative(opts.cwd, outPath) || outPath}`);
  return outPath;
}

async function collect(tsPath: string): Promise<{
  events: EventDescriptor[];
  listeners: ListenerDescriptor[];
}> {
  const url = pathToFileURL(tsPath).href;
  let mod: Record<string, unknown>;
  try {
    mod = (await import(url)) as Record<string, unknown>;
  } catch {
    return { events: [], listeners: [] };
  }
  const events: EventDescriptor[] = [];
  const listeners: ListenerDescriptor[] = [];
  for (const [key, value] of Object.entries(mod)) {
    if (!value || typeof value !== "object") continue;
    const v = value as { name?: string; event?: string };
    if (key.startsWith("__event_") && typeof v.name === "string") {
      events.push({ name: v.name, modulePath: tsPath });
    } else if (key.startsWith("__listener_") && typeof v.event === "string") {
      listeners.push({
        event: v.event,
        modulePath: tsPath,
        exportName: key.slice("__listener_".length),
      });
    }
  }
  return { events, listeners };
}

function renderBus(
  events: readonly EventDescriptor[],
  listeners: readonly ListenerDescriptor[],
  outPath: string
): string {
  // Type imports for event payload types (the struct names line up with
  // the type aliases the struct emitter declares).
  const typeImportsByPath = new Map<string, Set<string>>();
  for (const e of events) {
    const rel = relativeImport(outPath, e.modulePath);
    const set = typeImportsByPath.get(rel) ?? new Set<string>();
    set.add(e.name);
    typeImportsByPath.set(rel, set);
  }
  const handlerImportsByPath = new Map<string, Set<string>>();
  for (const l of listeners) {
    const rel = relativeImport(outPath, l.modulePath);
    const set = handlerImportsByPath.get(rel) ?? new Set<string>();
    set.add(l.exportName);
    handlerImportsByPath.set(rel, set);
  }

  const typeImportLines = [...typeImportsByPath].map(
    ([rel, names]) => `import type { ${[...names].join(", ")} } from ${JSON.stringify(rel)};`
  );
  const handlerImportLines = [...handlerImportsByPath].map(
    ([rel, names]) => `import { ${[...names].join(", ")} } from ${JSON.stringify(rel)};`
  );

  const eventNames = events.map((e) => JSON.stringify(e.name)).join(" | ") || "never";

  const payloadMapEntries = events
    .map((e) => `  ${JSON.stringify(e.name)}: ${e.name};`)
    .join("\n");

  // Group listeners by event for the dispatch table.
  const byEvent = new Map<string, string[]>();
  for (const l of listeners) {
    const arr = byEvent.get(l.event) ?? [];
    arr.push(l.exportName);
    byEvent.set(l.event, arr);
  }
  const tableEntries = [...byEvent]
    .map(
      ([event, hs]) =>
        `  ${JSON.stringify(event)}: [${hs.join(", ")}] as ((payload: unknown) => unknown)[]`
    )
    .join(",\n");

  return `// AUTO-GENERATED by bunny — do not edit by hand.
${typeImportLines.join("\n")}
${handlerImportLines.join("\n")}

export type EventName = ${eventNames};

export interface EventPayloads {
${payloadMapEntries}
}

const listeners: Record<string, ((payload: unknown) => unknown)[]> = {
${tableEntries}
};

/** Subscribe to an event at runtime. Returns an unsubscribe function. */
export function subscribe<K extends EventName>(
  event: K,
  handler: (payload: EventPayloads[K]) => unknown
): () => void {
  const arr = (listeners[event] ??= []);
  arr.push(handler as (payload: unknown) => unknown);
  return () => {
    const i = arr.indexOf(handler as (payload: unknown) => unknown);
    if (i >= 0) arr.splice(i, 1);
  };
}

/** Emit an event. Awaits every registered listener in registration order. */
export async function emit<K extends EventName>(
  event: K,
  payload: EventPayloads[K]
): Promise<void> {
  for (const h of listeners[event] ?? []) await h(payload);
}
`;
}

function relativeImport(from: string, to: string): string {
  const rel = path.relative(path.dirname(from), to);
  const norm = rel.startsWith(".") ? rel : `./${rel}`;
  return norm.replace(/\\/g, "/");
}
