/**
 * Aggregate `#[get/post/...]` route descriptors into a Bun.serve-ready
 * routes module.
 *
 *   bunny routes -s '**\/*.tsb' -o routes.ts
 *
 * Walks every `__route_*` export from compiled .tsb files and emits a
 * `routes` object indexed by path. Paths with a single method become a
 * direct handler reference; paths with multiple methods become a
 * `{ GET: ..., POST: ... }` map — both shapes Bun.serve accepts.
 */
import * as path from "node:path";
import { pathToFileURL } from "node:url";
import { buildProject } from "./compile.ts";

export interface RoutesAssemblerOptions {
  sourceGlobs: string[];
  cwd: string;
  output?: string;
  macroModules?: string[];
  log?: (msg: string) => void;
}

interface RouteDescriptor {
  method: string;
  path: string;
  params: { name: string; type: string }[];
  modulePath: string;
  exportName: string;
}

export async function buildRoutes(opts: RoutesAssemblerOptions): Promise<string> {
  const log = opts.log ?? ((m) => console.log(m));
  const outputs = await buildProject({
    sourceGlobs: opts.sourceGlobs,
    cwd: opts.cwd,
    macroModules: opts.macroModules,
    log,
  });

  const routes: RouteDescriptor[] = [];
  for (const tsPath of outputs) {
    for (const r of await collect(tsPath)) routes.push(r);
  }

  const outPath = path.resolve(opts.cwd, opts.output ?? "routes.ts");
  await Bun.write(outPath, renderRoutes(routes, outPath));
  log(`wrote ${path.relative(opts.cwd, outPath) || outPath}`);
  return outPath;
}

async function collect(tsPath: string): Promise<RouteDescriptor[]> {
  const url = pathToFileURL(tsPath).href;
  let mod: Record<string, unknown>;
  try {
    mod = (await import(url)) as Record<string, unknown>;
  } catch {
    return [];
  }
  const out: RouteDescriptor[] = [];
  for (const [key, value] of Object.entries(mod)) {
    if (!key.startsWith("__route_")) continue;
    if (!value || typeof value !== "object") continue;
    const v = value as {
      method?: string;
      path?: string;
      params?: { name: string; type: string }[];
    };
    if (typeof v.method !== "string" || typeof v.path !== "string") continue;
    out.push({
      method: v.method,
      path: v.path,
      params: v.params ?? [],
      modulePath: tsPath,
      exportName: key.slice("__route_".length),
    });
  }
  return out;
}

function renderRoutes(routes: readonly RouteDescriptor[], outPath: string): string {
  const importsByPath = new Map<string, Set<string>>();
  for (const r of routes) {
    const rel = relativeImport(outPath, r.modulePath);
    const set = importsByPath.get(rel) ?? new Set<string>();
    set.add(r.exportName);
    importsByPath.set(rel, set);
  }
  const importLines = [...importsByPath].map(
    ([rel, names]) => `import { ${[...names].join(", ")} } from ${JSON.stringify(rel)};`
  );

  // Group by path; each path either gets a single handler ref or a
  // method→handler object literal.
  const byPath = new Map<string, RouteDescriptor[]>();
  for (const r of routes) {
    const arr = byPath.get(r.path) ?? [];
    arr.push(r);
    byPath.set(r.path, arr);
  }

  // Always emit method-keyed form. Bun.serve treats a bare handler as
  // accepting every method; method-keyed responds with 405 to anything
  // unregistered, which is what REST callers expect.
  const entries = [...byPath]
    .map(([p, rs]) => {
      const methodMap = rs
        .map((r) => `    ${r.method}: ${methodAdapter(r)}`)
        .join(",\n");
      return `  ${JSON.stringify(p)}: {\n${methodMap}\n  }`;
    })
    .join(",\n");

  return `// AUTO-GENERATED by bunny — do not edit by hand.
${importLines.join("\n")}

/**
 * Bun.serve-ready route table. Each value is a request handler that
 * adapts the user's typed route function (which takes plain params
 * extracted from the URL) into the (req) => Response shape Bun expects.
 */
export const routes = {
${entries}
} as const;
`;
}

/**
 * Wrap a user route function so Bun's request handler shape (`req` →
 * `Response`) flows into the user's typed parameters.
 *
 * Each function param binds as one of:
 *   - **path param** — name matches a `:name` segment in the URL; pulled
 *     from `req.params.name` (Bun populates this on `BunRequest`).
 *   - **body** — non-path param on POST/PUT/PATCH; the request body is
 *     parsed as JSON and passed as the next positional.
 *   - **query** — non-path param on any other method; pulled from the
 *     URL's query string.
 */
function methodAdapter(r: RouteDescriptor): string {
  const pathParamNames = new Set(
    [...r.path.matchAll(/:([A-Za-z_][A-Za-z0-9_]*)/g)].map((m) => m[1]!)
  );
  const hasBody = ["POST", "PUT", "PATCH"].includes(r.method);
  const args: string[] = [];
  let bodyBound = false;
  for (const p of r.params) {
    if (pathParamNames.has(p.name)) {
      args.push(`(req as any).params?.${p.name}`);
    } else if (hasBody && !bodyBound) {
      // Body deserialisation is JSON; the user's function does its own
      // runtime validation via the struct's `new` factory, so we cast
      // to `any` and let the function signature enforce the shape.
      args.push(`(body as any)`);
      bodyBound = true;
    } else {
      args.push(
        `new URL(req.url).searchParams.get(${JSON.stringify(p.name)}) ?? undefined`
      );
    }
  }
  const call = `${r.exportName}(${args.join(", ")})`;
  const responseExpr = `Response.json(${call})`;
  if (bodyBound) {
    return `async (req: Request) => { const body = await req.json(); return ${responseExpr}; }`;
  }
  return `(req: Request) => ${responseExpr}`;
}

function relativeImport(from: string, to: string): string {
  const rel = path.relative(path.dirname(from), to);
  const norm = rel.startsWith(".") ? rel : `./${rel}`;
  return norm.replace(/\\/g, "/");
}
