// AUTO-GENERATED by bunny — do not edit by hand.
import { addBook, findBook, listBooks, statsAuthors, statsCount } from "./commands/BookCommands.ts";

export interface CommandSpec {
  description: string;
  params: { name: string; type: string }[];
  handler: (...args: unknown[]) => unknown;
}

export const commands: Record<string, CommandSpec> = {
  "add": { description: "Add a book to the library", params: [{"name":"isbn","type":"string"},{"name":"title","type":"string"},{"name":"author","type":"string"},{"name":"copies","type":"number"}], handler: addBook as unknown as (...args: unknown[]) => unknown },
  "find": { description: "Find a book by id", params: [{"name":"id","type":"string"}], handler: findBook as unknown as (...args: unknown[]) => unknown },
  "list": { description: "List every book on the shelf", params: [], handler: listBooks as unknown as (...args: unknown[]) => unknown },
  "stats:authors": { description: "List unique authors", params: [], handler: statsAuthors as unknown as (...args: unknown[]) => unknown },
  "stats:count": { description: "Show the count of books on the shelf", params: [], handler: statsCount as unknown as (...args: unknown[]) => unknown }
};

/**
 * Dispatch a positional argv against the command table. Coerces each
 * positional value to the parameter's declared type (`string`,
 * `number`, `boolean`); other types pass through as strings.
 */
export async function dispatch(argv: readonly string[]): Promise<unknown> {
  const [name, ...rest] = argv;
  if (!name) {
    printHelp();
    return undefined;
  }
  if (name === "--help" || name === "-h" || name === "help") {
    printHelp();
    return undefined;
  }
  const cmd = commands[name];
  if (!cmd) {
    process.stderr.write(`unknown command: ${name}\n`);
    printHelp();
    process.exitCode = 1;
    return undefined;
  }
  const coerced = cmd.params.map((p, i) => coerce(rest[i], p.type));
  return await cmd.handler(...coerced);
}

function coerce(raw: string | undefined, type: string): unknown {
  if (raw === undefined) return undefined;
  const t = type.trim();
  if (t === "number") return Number(raw);
  if (t === "boolean") return raw === "true" || raw === "1";
  return raw;
}

function printHelp(): void {
  const rows = Object.entries(commands).map(([name, spec]) => {
    const sig = spec.params.map((p) => `<${p.name}>`).join(" ");
    return `  ${name} ${sig}${spec.description ? "  — " + spec.description : ""}`;
  });
  process.stdout.write("Commands:\n" + rows.join("\n") + "\n");
}
