#!/usr/bin/env bun
/**
 * Self-contained CLI example. The dispatcher is generated by:
 *
 *   bunny cli -s '**\/*.tsb' -o cli-app.ts
 *
 * This file just forwards argv into `dispatch(...)`.
 */
import { dispatch } from "./cli-app.ts";

await dispatch(process.argv.slice(2));
