// AUTO-GENERATED by bunny — do not edit by hand.
import type { BookAdded } from "./events/BookAdded.ts";
import { logBookAdded } from "./listeners/AuditLog.ts";

export type EventName = "BookAdded";

export interface EventPayloads {
  "BookAdded": BookAdded;
}

const listeners: Record<string, ((payload: unknown) => unknown)[]> = {
  "BookAdded": [logBookAdded] as ((payload: unknown) => unknown)[]
};

/** Subscribe to an event at runtime. Returns an unsubscribe function. */
export function subscribe<K extends EventName>(
  event: K,
  handler: (payload: EventPayloads[K]) => unknown
): () => void {
  const arr = (listeners[event] ??= []);
  arr.push(handler as (payload: unknown) => unknown);
  return () => {
    const i = arr.indexOf(handler as (payload: unknown) => unknown);
    if (i >= 0) arr.splice(i, 1);
  };
}

/** Emit an event. Awaits every registered listener in registration order. */
export async function emit<K extends EventName>(
  event: K,
  payload: EventPayloads[K]
): Promise<void> {
  for (const h of listeners[event] ?? []) await h(payload);
}
