// AUTO-GENERATED by bunny — do not edit by hand.
import type { createTodo as _createTodo_t, deleteTodo as _deleteTodo_t, listTodos as _listTodos_t, toggleTodo as _toggleTodo_t } from "./controllers/TodosController.ts";

export class BunnyClientError extends Error {
  constructor(public readonly status: number, message: string) {
    super(message);
    this.name = "BunnyClientError";
  }
}

/**
 * Base URL prepended to every request path. Reads from the
 * `BUNNY_BASE_URL` env var when running on Node/Bun; defaults to the
 * empty string so the browser sends relative requests to its own
 * origin. Override at runtime by assigning to `baseUrl`.
 */
export let baseUrl: string =
  typeof process !== "undefined" && (process as { env?: Record<string, string | undefined> }).env?.BUNNY_BASE_URL
    ? (process as { env: Record<string, string | undefined> }).env.BUNNY_BASE_URL!
    : "";

async function call(
  method: string,
  url: string,
  options?: { body?: unknown; query?: Record<string, unknown> }
): Promise<unknown> {
  let finalUrl = baseUrl + url;
  if (options?.query) {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(options.query)) {
      if (v !== undefined && v !== null) qs.append(k, String(v));
    }
    const s = qs.toString();
    if (s.length > 0) finalUrl += "?" + s;
  }
  const init: RequestInit = { method };
  if (options?.body !== undefined) {
    init.headers = { "Content-Type": "application/json" };
    init.body = JSON.stringify(options.body);
  }
  const res = await fetch(finalUrl, init);
  if (!res.ok) {
    throw new BunnyClientError(res.status, `${method} ${url} failed: ${res.status}`);
  }
  // 204s have no body.
  if (res.status === 204) return undefined;
  const text = await res.text();
  return text.length === 0 ? undefined : JSON.parse(text);
}

export async function createTodo(body: Parameters<typeof _createTodo_t>[0]): Promise<Awaited<ReturnType<typeof _createTodo_t>>> {
  return (await call("POST", `/api/todos`, { body: body })) as Awaited<ReturnType<typeof _createTodo_t>>;
}

export async function deleteTodo(id: Parameters<typeof _deleteTodo_t>[0]): Promise<Awaited<ReturnType<typeof _deleteTodo_t>>> {
  return (await call("DELETE", `/api/todos/${encodeURIComponent(String(id))}`)) as Awaited<ReturnType<typeof _deleteTodo_t>>;
}

export async function listTodos(): Promise<Awaited<ReturnType<typeof _listTodos_t>>> {
  return (await call("GET", `/api/todos`)) as Awaited<ReturnType<typeof _listTodos_t>>;
}

export async function toggleTodo(id: Parameters<typeof _toggleTodo_t>[0]): Promise<Awaited<ReturnType<typeof _toggleTodo_t>>> {
  return (await call("PATCH", `/api/todos/${encodeURIComponent(String(id))}/toggle`)) as Awaited<ReturnType<typeof _toggleTodo_t>>;
}
