// AUTO-GENERATED by bunny — do not edit by hand.
import { createTodo, deleteTodo, listTodos, toggleTodo } from "./controllers/TodosController.ts";

/**
 * Bun.serve-ready route table. Each value is a request handler that
 * adapts the user's typed route function (which takes plain params
 * extracted from the URL) into the (req) => Response shape Bun expects.
 */
export const routes = {
  "/api/todos": {
    POST: async (req: Request) => { const body = await req.json(); return Response.json(createTodo((body as any))); },
    GET: (req: Request) => Response.json(listTodos())
  },
  "/api/todos/:id": {
    DELETE: (req: Request) => Response.json(deleteTodo((req as any).params?.id))
  },
  "/api/todos/:id/toggle": {
    PATCH: (req: Request) => Response.json(toggleTodo((req as any).params?.id))
  }
} as const;
