// AUTO-GENERATED by bunny. Provides ambient types and function
// signatures referenced by compiled .ts files. The matching runtime
// lives in `bunny.runtime.ts` and is loaded via a side-effect import
// at the top of every compiled module that uses Result.
declare global {
  type Result<T, E> = { ok: true; value: T } | { ok: false; error: E };
  type ConstraintError = { field: string; message: string };
  function Ok<T>(value: T): Result<T, never>;
  function Err<E>(error: E): Result<never, E>;
  function isOk<T, E>(r: Result<T, E>): r is { ok: true; value: T };
  function isErr<T, E>(r: Result<T, E>): r is { ok: false; error: E };
  function unwrap<T, E>(r: Result<T, E>): T;
  function unwrapOr<T, E>(r: Result<T, E>, fallback: T): T;
  function mapResult<T, U, E>(r: Result<T, E>, fn: (value: T) => U): Result<U, E>;
  function mapErr<T, E, F>(r: Result<T, E>, fn: (error: E) => F): Result<T, F>;
  function andThen<T, U, E>(r: Result<T, E>, fn: (value: T) => Result<U, E>): Result<U, E>;
}
export {};
