// AUTO-GENERATED by bunny — do not edit by hand.
import { createProduct, getProduct, listProducts } from "./controllers/ProductsController.ts";

/**
 * Bun.serve-ready route table. Each value is a request handler that
 * adapts the user's typed route function (which takes plain params
 * extracted from the URL) into the (req) => Response shape Bun expects.
 */
export const routes = {
  "/products": {
    POST: async (req: Request) => { const body = await req.json(); return Response.json(createProduct((body as any))); },
    GET: (req: Request) => Response.json(listProducts())
  },
  "/products/:id": {
    GET: (req: Request) => Response.json(getProduct((req as any).params?.id))
  }
} as const;
