#!/usr/bin/env bun
/**
 * Entry point. The `routes` table is regenerated by:
 *
 *   bunny routes -s '**\/*.tsb' -o routes.ts
 *
 * The OpenAPI spec is regenerated by:
 *
 *   bunny openapi -s '**\/*.tsb' -o openapi.json
 */
import { routes } from "./routes.ts";

const server = Bun.serve({
  port: 3000,
  routes,
});

console.log(`api listening on http://localhost:${server.port}`);
