import * as path from "node:path";
import { Asserter } from "./internal/asserter.ts";
import {
  type DiscoverOptions,
  discoverControllers,
  discoverServices,
  loadProject,
} from "./internal/discover.ts";
import { relativeImport, str } from "./internal/emit.ts";
import { normalizePath } from "./internal/path.ts";
import { extractRouteTypes } from "./internal/route-types.ts";
import { emitWiring } from "./internal/wiring.ts";

export interface GenerateBunOptions extends DiscoverOptions {
  /**
   * Directory the generated files will live in. The codegen writes two
   * files here:
   *
   *   {outDir}/app.ts      DI wiring — module-level service + controller
   *                        singletons with `@inject` fields supplied
   *                        positionally to each constructor. Re-exported
   *                        so anything else can grab the same instance.
   *   {outDir}/routes.ts   Validators + a spreadable `handlers` object
   *                        for `Bun.serve({ routes })`. Imports its
   *                        instances from `./app.ts`.
   */
  outDir: string;
  validate?: boolean;
  runtimeImport?: string;
  /**
   * Active profile for `@profile`-tagged services. Defaults to `"default"`.
   */
  profile?: string;
}

export interface GenerateBunOutput {
  /** Source for `{outDir}/app.ts`. */
  app: string;
  /** Source for `{outDir}/routes.ts`. */
  routes: string;
}

/**
 * Generate a two-file self-contained Bun app from the discovered
 * `@controller` / `@provides` classes. The output is split so that
 * application wiring (DI) and request plumbing (routes + validators) live
 * in separate modules — closer to how a Spring-style app would lay things
 * out by hand.
 */
export function generateBun(options: GenerateBunOptions): GenerateBunOutput {
  const validate = options.validate !== false;
  const runtimeImport = options.runtimeImport ?? "@flying-dice/bunny";

  const project = loadProject(options);
  const controllers = discoverControllers(project);
  const services = discoverServices(project);
  const asserter = new Asserter();
  const wiring = emitWiring(services, controllers, {
    exported: true,
    profile: options.profile,
  });

  // Both generated files live in `outDir`; relative imports back to the
  // user's source files compute identically from either, so we only need one.
  const appPath = path.join(options.outDir, "app.ts");

  // -------------------------------------------------------------------------
  // Per-route metadata + validator emission (drives the asserter).
  // -------------------------------------------------------------------------

  type Entry = {
    instance: string;
    methodName: string;
    httpMethod: string;
    fullPath: string;
    paramsFn: string | null;
    queryFn: string | null;
    bodyFn: string | null;
  };
  const entries: Entry[] = [];
  const routeValidatorDecls: string[] = [];

  for (const c of controllers) {
    const inst = wiring.instanceFor.get(c.className)!;
    for (const r of c.routes) {
      const types = validate ? extractRouteTypes(r.method) : null;
      const paramsFn = types?.params
        ? emitValidator(`validate_${r.methodName}_params`, types.params)
        : null;
      const queryFn = types?.query
        ? emitValidator(`validate_${r.methodName}_query`, types.query)
        : null;
      const bodyFn = types?.body
        ? emitValidator(`validate_${r.methodName}_body`, types.body)
        : null;
      entries.push({
        instance: inst,
        methodName: r.methodName,
        httpMethod: r.httpMethod,
        fullPath: normalizePath(r.path),
        paramsFn,
        queryFn,
        bodyFn,
      });
    }
  }

  function emitValidator(name: string, type: import("ts-morph").Type): string {
    routeValidatorDecls.push(asserter.emitRouteValidator(name, type));
    return name;
  }

  const componentDecls = validate ? asserter.emitNamedFunctions() : [];

  // -------------------------------------------------------------------------
  // app.ts — services, controllers, @inject wiring.
  // -------------------------------------------------------------------------

  const appLines: string[] = [];
  appLines.push("// AUTO-GENERATED by bunny — do not edit by hand.");
  appLines.push("//");
  appLines.push("// Application wiring: every @provides singleton and every @controller, with");
  appLines.push("// @inject fields supplied as constructor arguments. Re-exported so the");
  appLines.push("// routes module (and any user code) can grab the same instances.");
  for (const c of controllers) {
    appLines.push(`import { ${c.className} } from ${str(relativeImport(appPath, c.filePath))};`);
  }
  for (const s of wiring.activeServices) {
    appLines.push(`import { ${s.className} } from ${str(relativeImport(appPath, s.filePath))};`);
  }
  if (wiring.lines.length) {
    appLines.push("");
    for (const l of wiring.lines) appLines.push(l);
  }
  appLines.push("");

  // -------------------------------------------------------------------------
  // routes.ts — validators + handlers, importing instances from app.ts.
  // -------------------------------------------------------------------------

  const routesLines: string[] = [];
  routesLines.push("// AUTO-GENERATED by bunny — do not edit by hand.");
  routesLines.push(`import type { BunRequest } from "bun";`);
  routesLines.push(
    validate
      ? `import { applyValidation, safeInvoke, AssertionError, FORMATS } from ${str(runtimeImport)};`
      : `import { safeInvoke } from ${str(runtimeImport)};`
  );

  // Import the instances we'll dispatch into.
  const instanceImports = [...new Set(entries.map((e) => e.instance))].sort();
  if (instanceImports.length) {
    routesLines.push(`import { ${instanceImports.join(", ")} } from "./app.ts";`);
  }

  if (validate) {
    if (componentDecls.length) {
      routesLines.push("");
      routesLines.push("// ---- Component validators ----");
      for (const d of componentDecls) routesLines.push(d);
    }
    if (routeValidatorDecls.length) {
      routesLines.push("");
      routesLines.push("// ---- Per-route validators ----");
      for (const d of routeValidatorDecls) routesLines.push(d);
    }
  }

  const byPath = new Map<string, Entry[]>();
  for (const e of entries) {
    const bucket = byPath.get(e.fullPath) ?? [];
    bucket.push(e);
    byPath.set(e.fullPath, bucket);
  }

  routesLines.push("");
  routesLines.push("/**");
  routesLines.push(" * Spreadable route handlers for `Bun.serve({ routes })`.");
  routesLines.push(" *");
  routesLines.push(' *   import handlers from "./routes";');
  routesLines.push(" *   Bun.serve({ routes: handlers });");
  routesLines.push(" *");
  routesLines.push(" * Merge with your own:");
  routesLines.push(
    ' *   Bun.serve({ routes: { ...handlers, "/health": () => new Response("ok") } });'
  );
  routesLines.push(" */");
  routesLines.push("export const handlers = {");

  for (const [fullPath, group] of byPath) {
    routesLines.push(`  ${str(fullPath)}: {`);
    for (const e of group) {
      const hasValidators = e.paramsFn || e.queryFn || e.bodyFn;
      const verb = e.httpMethod.toUpperCase();
      routesLines.push(`    ${verb}: (req: BunRequest) =>`);
      routesLines.push(`      safeInvoke(async () => {`);
      routesLines.push(`        const r = req as any;`);
      routesLines.push(`        r.query = Object.fromEntries(new URL(req.url).searchParams);`);
      if (hasValidators) {
        routesLines.push(`        await applyValidation(r, {`);
        if (e.paramsFn) routesLines.push(`          params: ${e.paramsFn},`);
        if (e.queryFn) routesLines.push(`          query: ${e.queryFn},`);
        if (e.bodyFn) routesLines.push(`          body: ${e.bodyFn},`);
        routesLines.push(`        });`);
      }
      routesLines.push(
        `        return await ${e.instance}.${e.methodName}(r as Parameters<typeof ${e.instance}.${e.methodName}>[0]);`
      );
      routesLines.push(`      }),`);
    }
    routesLines.push(`  },`);
  }

  routesLines.push("};");
  routesLines.push("");
  routesLines.push("export default handlers;");
  routesLines.push("");

  return { app: appLines.join("\n"), routes: routesLines.join("\n") };
}
